var annotated_dup =
[
    [ "gazebo", "namespacegazebo.html", [
      [ "ApplyExternalWrench", "classgazebo_1_1ApplyExternalWrench.html", "classgazebo_1_1ApplyExternalWrench" ],
      [ "ConfigurationOverride", "classgazebo_1_1ConfigurationOverride.html", "classgazebo_1_1ConfigurationOverride" ],
      [ "GazeboYarpBaseState", "classgazebo_1_1GazeboYarpBaseState.html", "classgazebo_1_1GazeboYarpBaseState" ],
      [ "GazeboYarpCamera", "classgazebo_1_1GazeboYarpCamera.html", "classgazebo_1_1GazeboYarpCamera" ],
      [ "GazeboYarpClock", "classgazebo_1_1GazeboYarpClock.html", "classgazebo_1_1GazeboYarpClock" ],
      [ "GazeboYarpContactLoadCellArray", "classgazebo_1_1GazeboYarpContactLoadCellArray.html", "classgazebo_1_1GazeboYarpContactLoadCellArray" ],
      [ "GazeboYarpControlBoard", "classgazebo_1_1GazeboYarpControlBoard.html", "classgazebo_1_1GazeboYarpControlBoard" ],
      [ "GazeboYarpDepthCamera", "classgazebo_1_1GazeboYarpDepthCamera.html", "classgazebo_1_1GazeboYarpDepthCamera" ],
      [ "GazeboYarpFakeControlBoard", "classgazebo_1_1GazeboYarpFakeControlBoard.html", "classgazebo_1_1GazeboYarpFakeControlBoard" ],
      [ "GazeboYarpForceTorque", "classgazebo_1_1GazeboYarpForceTorque.html", "classgazebo_1_1GazeboYarpForceTorque" ],
      [ "GazeboYarpIMU", "classgazebo_1_1GazeboYarpIMU.html", "classgazebo_1_1GazeboYarpIMU" ],
      [ "GazeboYarpInertialMTB", "classgazebo_1_1GazeboYarpInertialMTB.html", "classgazebo_1_1GazeboYarpInertialMTB" ],
      [ "GazeboYarpInertialMTBPart", "classgazebo_1_1GazeboYarpInertialMTBPart.html", "classgazebo_1_1GazeboYarpInertialMTBPart" ],
      [ "GazeboYarpLaserSensor", "classgazebo_1_1GazeboYarpLaserSensor.html", "classgazebo_1_1GazeboYarpLaserSensor" ],
      [ "GazeboYarpMaisSensor", "classgazebo_1_1GazeboYarpMaisSensor.html", "classgazebo_1_1GazeboYarpMaisSensor" ],
      [ "GazeboYarpModelPosePublisher", "classgazebo_1_1GazeboYarpModelPosePublisher.html", "classgazebo_1_1GazeboYarpModelPosePublisher" ],
      [ "GazeboYarpMultiCamera", "classgazebo_1_1GazeboYarpMultiCamera.html", "classgazebo_1_1GazeboYarpMultiCamera" ],
      [ "GazeboYarpRobotInterface", "classgazebo_1_1GazeboYarpRobotInterface.html", "classgazebo_1_1GazeboYarpRobotInterface" ],
      [ "LinkAttacher", "classgazebo_1_1LinkAttacher.html", "classgazebo_1_1LinkAttacher" ],
      [ "MultiCameraPlugin", "classgazebo_1_1MultiCameraPlugin.html", "classgazebo_1_1MultiCameraPlugin" ],
      [ "ShowModelCoM", "classgazebo_1_1ShowModelCoM.html", "classgazebo_1_1ShowModelCoM" ],
      [ "VideoTexture", "classgazebo_1_1VideoTexture.html", "classgazebo_1_1VideoTexture" ],
      [ "WorldInterface", "classgazebo_1_1WorldInterface.html", "classgazebo_1_1WorldInterface" ]
    ] ],
    [ "GazeboYarpPlugins", "namespaceGazeboYarpPlugins.html", [
      [ "ClockServer", "classGazeboYarpPlugins_1_1ClockServer.html", "classGazeboYarpPlugins_1_1ClockServer" ],
      [ "ClockServer_continueSimulation_helper", "classGazeboYarpPlugins_1_1ClockServer__continueSimulation__helper.html", "classGazeboYarpPlugins_1_1ClockServer__continueSimulation__helper" ],
      [ "ClockServer_getSimulationTime_helper", "classGazeboYarpPlugins_1_1ClockServer__getSimulationTime__helper.html", "classGazeboYarpPlugins_1_1ClockServer__getSimulationTime__helper" ],
      [ "ClockServer_getStepSize_helper", "classGazeboYarpPlugins_1_1ClockServer__getStepSize__helper.html", "classGazeboYarpPlugins_1_1ClockServer__getStepSize__helper" ],
      [ "ClockServer_pauseSimulation_helper", "classGazeboYarpPlugins_1_1ClockServer__pauseSimulation__helper.html", "classGazeboYarpPlugins_1_1ClockServer__pauseSimulation__helper" ],
      [ "ClockServer_resetSimulation_helper", "classGazeboYarpPlugins_1_1ClockServer__resetSimulation__helper.html", "classGazeboYarpPlugins_1_1ClockServer__resetSimulation__helper" ],
      [ "ClockServer_resetSimulationState_helper", "classGazeboYarpPlugins_1_1ClockServer__resetSimulationState__helper.html", "classGazeboYarpPlugins_1_1ClockServer__resetSimulationState__helper" ],
      [ "ClockServer_resetSimulationTime_helper", "classGazeboYarpPlugins_1_1ClockServer__resetSimulationTime__helper.html", "classGazeboYarpPlugins_1_1ClockServer__resetSimulationTime__helper" ],
      [ "ClockServer_stepSimulation_helper", "classGazeboYarpPlugins_1_1ClockServer__stepSimulation__helper.html", "classGazeboYarpPlugins_1_1ClockServer__stepSimulation__helper" ],
      [ "ClockServer_stepSimulationAndWait_helper", "classGazeboYarpPlugins_1_1ClockServer__stepSimulationAndWait__helper.html", "classGazeboYarpPlugins_1_1ClockServer__stepSimulationAndWait__helper" ],
      [ "ClockServerImpl", "classGazeboYarpPlugins_1_1ClockServerImpl.html", "classGazeboYarpPlugins_1_1ClockServerImpl" ],
      [ "Color", "classGazeboYarpPlugins_1_1Color.html", "classGazeboYarpPlugins_1_1Color" ],
      [ "Handler", "classGazeboYarpPlugins_1_1Handler.html", "classGazeboYarpPlugins_1_1Handler" ],
      [ "LinkAttacherServer", "classGazeboYarpPlugins_1_1LinkAttacherServer.html", "classGazeboYarpPlugins_1_1LinkAttacherServer" ],
      [ "LinkAttacherServer_attachUnscoped_helper", "classGazeboYarpPlugins_1_1LinkAttacherServer__attachUnscoped__helper.html", "classGazeboYarpPlugins_1_1LinkAttacherServer__attachUnscoped__helper" ],
      [ "LinkAttacherServer_detachUnscoped_helper", "classGazeboYarpPlugins_1_1LinkAttacherServer__detachUnscoped__helper.html", "classGazeboYarpPlugins_1_1LinkAttacherServer__detachUnscoped__helper" ],
      [ "LinkAttacherServer_enableGravity_helper", "classGazeboYarpPlugins_1_1LinkAttacherServer__enableGravity__helper.html", "classGazeboYarpPlugins_1_1LinkAttacherServer__enableGravity__helper" ],
      [ "Pose", "classGazeboYarpPlugins_1_1Pose.html", "classGazeboYarpPlugins_1_1Pose" ],
      [ "WorldInterfaceServer", "classGazeboYarpPlugins_1_1WorldInterfaceServer.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer" ],
      [ "WorldInterfaceServer_attach_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__attach__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__attach__helper" ],
      [ "WorldInterfaceServer_changeColor_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__changeColor__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__changeColor__helper" ],
      [ "WorldInterfaceServer_deleteAll_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__deleteAll__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__deleteAll__helper" ],
      [ "WorldInterfaceServer_deleteObject_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__deleteObject__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__deleteObject__helper" ],
      [ "WorldInterfaceServer_detach_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__detach__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__detach__helper" ],
      [ "WorldInterfaceServer_enableCollision_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__enableCollision__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__enableCollision__helper" ],
      [ "WorldInterfaceServer_enableGravity_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__enableGravity__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__enableGravity__helper" ],
      [ "WorldInterfaceServer_getList_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__getList__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__getList__helper" ],
      [ "WorldInterfaceServer_getPose_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__getPose__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__getPose__helper" ],
      [ "WorldInterfaceServer_loadModelFromFile_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__loadModelFromFile__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__loadModelFromFile__helper" ],
      [ "WorldInterfaceServer_loadModelFromFileWithPose_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__loadModelFromFileWithPose__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__loadModelFromFileWithPose__helper" ],
      [ "WorldInterfaceServer_makeBox_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__makeBox__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__makeBox__helper" ],
      [ "WorldInterfaceServer_makeCylinder_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__makeCylinder__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__makeCylinder__helper" ],
      [ "WorldInterfaceServer_makeFrame_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__makeFrame__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__makeFrame__helper" ],
      [ "WorldInterfaceServer_makeSphere_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__makeSphere__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__makeSphere__helper" ],
      [ "WorldInterfaceServer_rename_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__rename__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__rename__helper" ],
      [ "WorldInterfaceServer_setPose_helper", "classGazeboYarpPlugins_1_1WorldInterfaceServer__setPose__helper.html", "classGazeboYarpPlugins_1_1WorldInterfaceServer__setPose__helper" ]
    ] ],
    [ "yarp", "namespaceyarp.html", [
      [ "dev", "namespaceyarp_1_1dev.html", [
        [ "GazeboYarpBaseStateDriver", "classyarp_1_1dev_1_1GazeboYarpBaseStateDriver.html", "classyarp_1_1dev_1_1GazeboYarpBaseStateDriver" ],
        [ "GazeboYarpCameraDriver", "classyarp_1_1dev_1_1GazeboYarpCameraDriver.html", "classyarp_1_1dev_1_1GazeboYarpCameraDriver" ],
        [ "GazeboYarpContactLoadCellArrayDriver", "classyarp_1_1dev_1_1GazeboYarpContactLoadCellArrayDriver.html", "classyarp_1_1dev_1_1GazeboYarpContactLoadCellArrayDriver" ],
        [ "GazeboYarpControlBoardDriver", "classyarp_1_1dev_1_1GazeboYarpControlBoardDriver.html", "classyarp_1_1dev_1_1GazeboYarpControlBoardDriver" ],
        [ "GazeboYarpDepthCameraDriver", "classyarp_1_1dev_1_1GazeboYarpDepthCameraDriver.html", "classyarp_1_1dev_1_1GazeboYarpDepthCameraDriver" ],
        [ "GazeboYarpFakeControlBoardDriver", "classyarp_1_1dev_1_1GazeboYarpFakeControlBoardDriver.html", "classyarp_1_1dev_1_1GazeboYarpFakeControlBoardDriver" ],
        [ "GazeboYarpForceTorqueDriver", "classyarp_1_1dev_1_1GazeboYarpForceTorqueDriver.html", "classyarp_1_1dev_1_1GazeboYarpForceTorqueDriver" ],
        [ "GazeboYarpIMUDriver", "classyarp_1_1dev_1_1GazeboYarpIMUDriver.html", "classyarp_1_1dev_1_1GazeboYarpIMUDriver" ],
        [ "GazeboYarpInertialMTBPartDriver", "classyarp_1_1dev_1_1GazeboYarpInertialMTBPartDriver.html", "classyarp_1_1dev_1_1GazeboYarpInertialMTBPartDriver" ],
        [ "GazeboYarpLaserSensorDriver", "classyarp_1_1dev_1_1GazeboYarpLaserSensorDriver.html", "classyarp_1_1dev_1_1GazeboYarpLaserSensorDriver" ],
        [ "GazeboYarpMaisSensorDriver", "classyarp_1_1dev_1_1GazeboYarpMaisSensorDriver.html", "classyarp_1_1dev_1_1GazeboYarpMaisSensorDriver" ],
        [ "GazeboYarpMultiCameraDriver", "classyarp_1_1dev_1_1GazeboYarpMultiCameraDriver.html", "classyarp_1_1dev_1_1GazeboYarpMultiCameraDriver" ],
        [ "PidControlTypeEnumHashFunction", "structyarp_1_1dev_1_1PidControlTypeEnumHashFunction.html", "structyarp_1_1dev_1_1PidControlTypeEnumHashFunction" ]
      ] ],
      [ "os", "namespaceyarp_1_1os.html", [
        [ "BufferedPort", "classyarp_1_1os_1_1BufferedPort.html", null ]
      ] ]
    ] ],
    [ "BaseCouplingHandler", "classBaseCouplingHandler.html", "classBaseCouplingHandler" ],
    [ "CerHandCouplingHandler", "classCerHandCouplingHandler.html", "classCerHandCouplingHandler" ],
    [ "ConstSpeedTrajectoryGenerator", "classConstSpeedTrajectoryGenerator.html", "classConstSpeedTrajectoryGenerator" ],
    [ "ExternalWrench", "classExternalWrench.html", "classExternalWrench" ],
    [ "EyesCouplingHandler", "classEyesCouplingHandler.html", "classEyesCouplingHandler" ],
    [ "FingersAbductionCouplingHandler", "classFingersAbductionCouplingHandler.html", "classFingersAbductionCouplingHandler" ],
    [ "GazeboYarpInertialMTBPartDriver", "classGazeboYarpInertialMTBPartDriver.html", null ],
    [ "GazeboYarpModelPosePublisherExample", "classGazeboYarpModelPosePublisherExample.html", "classGazeboYarpModelPosePublisherExample" ],
    [ "HandMk3CouplingHandler", "classHandMk3CouplingHandler.html", "classHandMk3CouplingHandler" ],
    [ "HandMk4CouplingHandler", "classHandMk4CouplingHandler.html", "classHandMk4CouplingHandler" ],
    [ "HandMk5CouplingHandler", "classHandMk5CouplingHandler.html", "classHandMk5CouplingHandler" ],
    [ "IndexCouplingHandler", "classIndexCouplingHandler.html", "classIndexCouplingHandler" ],
    [ "LinkAttacherServerImpl", "classLinkAttacherServerImpl.html", "classLinkAttacherServerImpl" ],
    [ "MiddleCouplingHandler", "classMiddleCouplingHandler.html", "classMiddleCouplingHandler" ],
    [ "MinJerkTrajectoryGenerator", "classMinJerkTrajectoryGenerator.html", "classMinJerkTrajectoryGenerator" ],
    [ "PinkyCouplingHandler", "classPinkyCouplingHandler.html", "classPinkyCouplingHandler" ],
    [ "RampFilter", "classRampFilter.html", "classRampFilter" ],
    [ "Range", "structRange.html", "structRange" ],
    [ "RPCServerThread", "classRPCServerThread.html", "classRPCServerThread" ],
    [ "SynchronizationHelper", "classSynchronizationHelper.html", "classSynchronizationHelper" ],
    [ "ThumbCouplingHandler", "classThumbCouplingHandler.html", "classThumbCouplingHandler" ],
    [ "TrajectoryGenerator", "classTrajectoryGenerator.html", "classTrajectoryGenerator" ],
    [ "TrapezoidalSpeedTrajectoryGenerator", "classTrapezoidalSpeedTrajectoryGenerator.html", "classTrapezoidalSpeedTrajectoryGenerator" ],
    [ "Watchdog", "classWatchdog.html", "classWatchdog" ],
    [ "WorldInterfaceServerImpl", "classWorldInterfaceServerImpl.html", "classWorldInterfaceServerImpl" ],
    [ "WorldProxy", "classWorldProxy.html", "classWorldProxy" ]
];