/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <GazeboYarpPlugins/ClockServer.h>

#include <yarp/os/idl/WireTypes.h>

namespace GazeboYarpPlugins {

class ClockServer_pauseSimulation_helper :
        public yarp::os::Portable
{
public:
    explicit ClockServer_pauseSimulation_helper();
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;
};

ClockServer_pauseSimulation_helper::ClockServer_pauseSimulation_helper()
{
}

bool ClockServer_pauseSimulation_helper::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(1)) {
        return false;
    }
    if (!writer.writeTag("pauseSimulation", 1, 1)) {
        return false;
    }
    return true;
}

bool ClockServer_pauseSimulation_helper::read(yarp::os::ConnectionReader& connection)
{
    YARP_UNUSED(connection);
    return true;
}

class ClockServer_continueSimulation_helper :
        public yarp::os::Portable
{
public:
    explicit ClockServer_continueSimulation_helper();
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;
};

ClockServer_continueSimulation_helper::ClockServer_continueSimulation_helper()
{
}

bool ClockServer_continueSimulation_helper::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(1)) {
        return false;
    }
    if (!writer.writeTag("continueSimulation", 1, 1)) {
        return false;
    }
    return true;
}

bool ClockServer_continueSimulation_helper::read(yarp::os::ConnectionReader& connection)
{
    YARP_UNUSED(connection);
    return true;
}

class ClockServer_stepSimulation_helper :
        public yarp::os::Portable
{
public:
    explicit ClockServer_stepSimulation_helper(const std::int32_t numberOfSteps);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    std::int32_t m_numberOfSteps;
};

ClockServer_stepSimulation_helper::ClockServer_stepSimulation_helper(const std::int32_t numberOfSteps) :
        m_numberOfSteps{numberOfSteps}
{
}

bool ClockServer_stepSimulation_helper::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(2)) {
        return false;
    }
    if (!writer.writeTag("stepSimulation", 1, 1)) {
        return false;
    }
    if (!writer.writeI32(m_numberOfSteps)) {
        return false;
    }
    return true;
}

bool ClockServer_stepSimulation_helper::read(yarp::os::ConnectionReader& connection)
{
    YARP_UNUSED(connection);
    return true;
}

class ClockServer_stepSimulationAndWait_helper :
        public yarp::os::Portable
{
public:
    explicit ClockServer_stepSimulationAndWait_helper(const std::int32_t numberOfSteps);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    std::int32_t m_numberOfSteps;
};

ClockServer_stepSimulationAndWait_helper::ClockServer_stepSimulationAndWait_helper(const std::int32_t numberOfSteps) :
        m_numberOfSteps{numberOfSteps}
{
}

bool ClockServer_stepSimulationAndWait_helper::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(2)) {
        return false;
    }
    if (!writer.writeTag("stepSimulationAndWait", 1, 1)) {
        return false;
    }
    if (!writer.writeI32(m_numberOfSteps)) {
        return false;
    }
    return true;
}

bool ClockServer_stepSimulationAndWait_helper::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListReturn()) {
        return false;
    }
    return true;
}

class ClockServer_resetSimulationTime_helper :
        public yarp::os::Portable
{
public:
    explicit ClockServer_resetSimulationTime_helper();
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;
};

ClockServer_resetSimulationTime_helper::ClockServer_resetSimulationTime_helper()
{
}

bool ClockServer_resetSimulationTime_helper::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(1)) {
        return false;
    }
    if (!writer.writeTag("resetSimulationTime", 1, 1)) {
        return false;
    }
    return true;
}

bool ClockServer_resetSimulationTime_helper::read(yarp::os::ConnectionReader& connection)
{
    YARP_UNUSED(connection);
    return true;
}

class ClockServer_getSimulationTime_helper :
        public yarp::os::Portable
{
public:
    explicit ClockServer_getSimulationTime_helper();
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    thread_local static double s_return_helper;
};

thread_local double ClockServer_getSimulationTime_helper::s_return_helper = {};

ClockServer_getSimulationTime_helper::ClockServer_getSimulationTime_helper()
{
    s_return_helper = {};
}

bool ClockServer_getSimulationTime_helper::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(1)) {
        return false;
    }
    if (!writer.writeTag("getSimulationTime", 1, 1)) {
        return false;
    }
    return true;
}

bool ClockServer_getSimulationTime_helper::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListReturn()) {
        return false;
    }
    if (!reader.readFloat64(s_return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

class ClockServer_getStepSize_helper :
        public yarp::os::Portable
{
public:
    explicit ClockServer_getStepSize_helper();
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    thread_local static double s_return_helper;
};

thread_local double ClockServer_getStepSize_helper::s_return_helper = {};

ClockServer_getStepSize_helper::ClockServer_getStepSize_helper()
{
    s_return_helper = {};
}

bool ClockServer_getStepSize_helper::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(1)) {
        return false;
    }
    if (!writer.writeTag("getStepSize", 1, 1)) {
        return false;
    }
    return true;
}

bool ClockServer_getStepSize_helper::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListReturn()) {
        return false;
    }
    if (!reader.readFloat64(s_return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

class ClockServer_resetSimulation_helper :
        public yarp::os::Portable
{
public:
    explicit ClockServer_resetSimulation_helper();
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;
};

ClockServer_resetSimulation_helper::ClockServer_resetSimulation_helper()
{
}

bool ClockServer_resetSimulation_helper::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(1)) {
        return false;
    }
    if (!writer.writeTag("resetSimulation", 1, 1)) {
        return false;
    }
    return true;
}

bool ClockServer_resetSimulation_helper::read(yarp::os::ConnectionReader& connection)
{
    YARP_UNUSED(connection);
    return true;
}

class ClockServer_resetSimulationState_helper :
        public yarp::os::Portable
{
public:
    explicit ClockServer_resetSimulationState_helper();
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;
};

ClockServer_resetSimulationState_helper::ClockServer_resetSimulationState_helper()
{
}

bool ClockServer_resetSimulationState_helper::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(1)) {
        return false;
    }
    if (!writer.writeTag("resetSimulationState", 1, 1)) {
        return false;
    }
    return true;
}

bool ClockServer_resetSimulationState_helper::read(yarp::os::ConnectionReader& connection)
{
    YARP_UNUSED(connection);
    return true;
}

// Constructor
ClockServer::ClockServer()
{
    yarp().setOwner(*this);
}

void ClockServer::pauseSimulation()
{
    ClockServer_pauseSimulation_helper helper{};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "void ClockServer::pauseSimulation()");
    }
    yarp().write(helper);
}

void ClockServer::continueSimulation()
{
    ClockServer_continueSimulation_helper helper{};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "void ClockServer::continueSimulation()");
    }
    yarp().write(helper);
}

void ClockServer::stepSimulation(const std::int32_t numberOfSteps)
{
    ClockServer_stepSimulation_helper helper{numberOfSteps};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "void ClockServer::stepSimulation(const std::int32_t numberOfSteps)");
    }
    yarp().write(helper);
}

void ClockServer::stepSimulationAndWait(const std::int32_t numberOfSteps)
{
    ClockServer_stepSimulationAndWait_helper helper{numberOfSteps};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "void ClockServer::stepSimulationAndWait(const std::int32_t numberOfSteps)");
    }
    yarp().write(helper, helper);
}

void ClockServer::resetSimulationTime()
{
    ClockServer_resetSimulationTime_helper helper{};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "void ClockServer::resetSimulationTime()");
    }
    yarp().write(helper);
}

double ClockServer::getSimulationTime()
{
    ClockServer_getSimulationTime_helper helper{};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "double ClockServer::getSimulationTime()");
    }
    bool ok = yarp().write(helper, helper);
    return ok ? ClockServer_getSimulationTime_helper::s_return_helper : double{};
}

double ClockServer::getStepSize()
{
    ClockServer_getStepSize_helper helper{};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "double ClockServer::getStepSize()");
    }
    bool ok = yarp().write(helper, helper);
    return ok ? ClockServer_getStepSize_helper::s_return_helper : double{};
}

void ClockServer::resetSimulation()
{
    ClockServer_resetSimulation_helper helper{};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "void ClockServer::resetSimulation()");
    }
    yarp().write(helper);
}

void ClockServer::resetSimulationState()
{
    ClockServer_resetSimulationState_helper helper{};
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", "void ClockServer::resetSimulationState()");
    }
    yarp().write(helper);
}

// help method
std::vector<std::string> ClockServer::help(const std::string& functionName)
{
    bool showAll = (functionName == "--all");
    std::vector<std::string> helpString;
    if (showAll) {
        helpString.emplace_back("*** Available commands:");
        helpString.emplace_back("pauseSimulation");
        helpString.emplace_back("continueSimulation");
        helpString.emplace_back("stepSimulation");
        helpString.emplace_back("stepSimulationAndWait");
        helpString.emplace_back("resetSimulationTime");
        helpString.emplace_back("getSimulationTime");
        helpString.emplace_back("getStepSize");
        helpString.emplace_back("resetSimulation");
        helpString.emplace_back("resetSimulationState");
        helpString.emplace_back("help");
    } else {
        if (functionName == "pauseSimulation") {
            helpString.emplace_back("void pauseSimulation() ");
            helpString.emplace_back("Pause the simulation if it was running ");
        }
        if (functionName == "continueSimulation") {
            helpString.emplace_back("void continueSimulation() ");
            helpString.emplace_back("Resume the simulation if it was paused ");
        }
        if (functionName == "stepSimulation") {
            helpString.emplace_back("void stepSimulation(const std::int32_t numberOfSteps = 1) ");
            helpString.emplace_back("Steps the simulation for the provided number of steps. ");
            helpString.emplace_back("The input parameter is the number of steps, not the time (Usually 1 step = 1ms but this is not guaranteed) ");
            helpString.emplace_back("@note: this function (will be) not blocking, i.e. it will return immediately. Currently calling this function ");
            helpString.emplace_back("twice before the previous call actually ends its computation gives and undefined behavior. ");
            helpString.emplace_back("@param numberOfSteps number of steps to simulate ");
        }
        if (functionName == "stepSimulationAndWait") {
            helpString.emplace_back("void stepSimulationAndWait(const std::int32_t numberOfSteps = 1) ");
            helpString.emplace_back("Steps the simulation for the provided number of steps. ");
            helpString.emplace_back("The input parameter is the number of steps, not the time (Usually 1 step = 1ms but this is not guaranteed) ");
            helpString.emplace_back("@note: this function is blocking ");
            helpString.emplace_back("@param numberOfSteps number of steps to simulate ");
        }
        if (functionName == "resetSimulationTime") {
            helpString.emplace_back("void resetSimulationTime() ");
            helpString.emplace_back("Reset the simulation time back to zero ");
        }
        if (functionName == "getSimulationTime") {
            helpString.emplace_back("double getSimulationTime() ");
            helpString.emplace_back("Get the current simulation time ");
            helpString.emplace_back("@return the simulation time. ");
        }
        if (functionName == "getStepSize") {
            helpString.emplace_back("double getStepSize() ");
            helpString.emplace_back("Get the current step size in seconds. ");
            helpString.emplace_back("@return the step size in seconds ");
        }
        if (functionName == "resetSimulation") {
            helpString.emplace_back("void resetSimulation() ");
            helpString.emplace_back("Reset the simulation state and time ");
        }
        if (functionName == "resetSimulationState") {
            helpString.emplace_back("void resetSimulationState() ");
            helpString.emplace_back("Reset the simulation state back to initial pose ");
        }
        if (functionName == "help") {
            helpString.emplace_back("std::vector<std::string> help(const std::string& functionName = \"--all\")");
            helpString.emplace_back("Return list of available commands, or help message for a specific function");
            helpString.emplace_back("@param functionName name of command for which to get a detailed description. If none or '--all' is provided, print list of available commands");
            helpString.emplace_back("@return list of strings (one string per line)");
        }
    }
    if (helpString.empty()) {
        helpString.emplace_back("Command not found");
    }
    return helpString;
}

// read from ConnectionReader
bool ClockServer::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    reader.expectAccept();
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }

    std::string tag = reader.readTag();
    bool direct = (tag == "__direct__");
    if (direct) {
        tag = reader.readTag();
    }
    while (!reader.isError()) {
        if (tag == "pauseSimulation") {
            if (!direct) {
                ClockServer_pauseSimulation_helper helper{};
                yarp().callback(helper, *this, "__direct__");
            } else {
                pauseSimulation();
            }
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeOnewayResponse()) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (tag == "continueSimulation") {
            if (!direct) {
                ClockServer_continueSimulation_helper helper{};
                yarp().callback(helper, *this, "__direct__");
            } else {
                continueSimulation();
            }
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeOnewayResponse()) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (tag == "stepSimulation") {
            std::int32_t numberOfSteps;
            if (!reader.readI32(numberOfSteps)) {
                numberOfSteps = 1;
            }
            if (!direct) {
                ClockServer_stepSimulation_helper helper{numberOfSteps};
                yarp().callback(helper, *this, "__direct__");
            } else {
                stepSimulation(numberOfSteps);
            }
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeOnewayResponse()) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (tag == "stepSimulationAndWait") {
            std::int32_t numberOfSteps;
            if (!reader.readI32(numberOfSteps)) {
                numberOfSteps = 1;
            }
            stepSimulationAndWait(numberOfSteps);
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeListHeader(0)) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (tag == "resetSimulationTime") {
            if (!direct) {
                ClockServer_resetSimulationTime_helper helper{};
                yarp().callback(helper, *this, "__direct__");
            } else {
                resetSimulationTime();
            }
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeOnewayResponse()) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (tag == "getSimulationTime") {
            ClockServer_getSimulationTime_helper::s_return_helper = getSimulationTime();
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeListHeader(1)) {
                    return false;
                }
                if (!writer.writeFloat64(ClockServer_getSimulationTime_helper::s_return_helper)) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (tag == "getStepSize") {
            ClockServer_getStepSize_helper::s_return_helper = getStepSize();
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeListHeader(1)) {
                    return false;
                }
                if (!writer.writeFloat64(ClockServer_getStepSize_helper::s_return_helper)) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (tag == "resetSimulation") {
            if (!direct) {
                ClockServer_resetSimulation_helper helper{};
                yarp().callback(helper, *this, "__direct__");
            } else {
                resetSimulation();
            }
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeOnewayResponse()) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (tag == "resetSimulationState") {
            if (!direct) {
                ClockServer_resetSimulationState_helper helper{};
                yarp().callback(helper, *this, "__direct__");
            } else {
                resetSimulationState();
            }
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeOnewayResponse()) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (tag == "help") {
            std::string functionName;
            if (!reader.readString(functionName)) {
                functionName = "--all";
            }
            auto help_strings = help(functionName);
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeListHeader(2)) {
                    return false;
                }
                if (!writer.writeTag("many", 1, 0)) {
                    return false;
                }
                if (!writer.writeListBegin(BOTTLE_TAG_INT32, static_cast<uint32_t>(help_strings.size()))) {
                    return false;
                }
                for (const auto& help_string : help_strings) {
                    if (!writer.writeString(help_string)) {
                        return false;
                    }
                }
                if (!writer.writeListEnd()) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (reader.noMore()) {
            reader.fail();
            return false;
        }
        std::string next_tag = reader.readTag();
        if (next_tag == "") {
            break;
        }
        tag.append("_").append(next_tag);
    }
    return false;
}

} // namespace GazeboYarpPlugins
